apiVersion: fission.io/v1
kind: Environment
metadata:
  name: {{ .Values.dynamiq.runtime.name }}
  namespace: {{ .Values.dynamiq.apps.namespace }}
spec:
  version: 3
  builder:
    command: build
    container:
      name: ""
      resources: {}
    image: fission/python-builder:latest
  imagepullsecret: docker-registry
  keeparchive: false
  poolsize: {{ .Values.dynamiq.runtime.poolsize }}
  resources:
    {{- toYaml .Values.dynamiq.runtime.resources | nindent 4 }}
  runtime:
    container:
      env:
        {{- toYaml .Values.dynamiq.runtime.env | nindent 8 }}
      name: {{ .Values.dynamiq.runtime.name }}
      resources: {}
    image: {{ .Values.dynamiq.runtime.image }}