{{- define "imagePullSecret" }}
{{- printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.dynamiq.imageCredentials.registry (printf "%s:%s" .Values.dynamiq.imageCredentials.username .Values.dynamiq.imageCredentials.password | b64enc) | b64enc }}
{{- end }}