kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "dynamiq:{{ include "nexus.serviceAccountName" . }}"
subjects:
  - kind: ServiceAccount
    name: {{ include "nexus.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: "dynamiq:{{ include "nexus.serviceAccountName" . }}"
  apiGroup: rbac.authorization.k8s.io
