apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "dynamiq:{{ include "nexus.serviceAccountName" . }}"
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
