apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus
  labels:
    app: nexus-service
data:
  {{- range $key, $value :=  .Values.configMapData }}
  {{ $key | quote }}: {{ $value | quote }}
  {{- end }}
