{{ if not (.Values.secretData) }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "nexus.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: dynamiq
  target:
    name: nexus
  dataFrom:
    - extract:
        key: DYNAMIQ-NEXUS
{{ end }}