{{ if .Values.secretData }}
{{ if .Values.secretData | length }}
apiVersion: v1
kind: Secret
metadata:
  name: nexus
  labels:
    app: nexus-service
stringData:
  {{- .Values.secretData | toYaml | nindent 2 }}
{{ end }}
{{ end }}