dynamiq:
  apps:
    namespace: apps

  imageCredentials:
    registry: https://index.docker.io/v1/
    username: ""
    password: ""

  runtime:
    name: app-env-v150
    image: dynamiqai/app-runtime:1.0.6
    env:
      - name: ENV
        value: prod
    poolsize: 3
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 512Mi
nexus:
  configMapData:
    ENV: prod
    SYNAPSE_URL: 'http://synapse.synapse.svc.cluster.local:80'
    CATALYST_URL: 'http://catalyst.catalyst.svc.cluster.local:80'
    APP_NAMESPACE: apps
    AUTH_ACCESS_TOKEN_TTL: 1h
    AUTH_REFRESH_TOKEN_TTL: 240h
    AUTH_VERIFICATION_TOKEN_TTL: 12h
    BILLING_ENABLED: 'false'
    FINE_TUNING_DOCKER_IMAGE: 'dynamiqai/fine-tuning:0.3.8'
    FINE_TUNING_IMAGE_PULL_SECRET: docker-registry
    FINE_TUNING_NAMESPACE: fine-tuning
    FINE_TUNING_SERVICE_ACCOUNT: fine-tuning
    IMAGE_BUILDER_DOCKER_IMAGE: 'gcr.io/kaniko-project/executor:v1.23.1'
    IMAGE_BUILDER_NAMESPACE: image-builder
    IMAGE_BUILDER_SERVICE_ACCOUNT: image-builder
    INFERENCE_NAMESPACE: inferences
    INFERENCE_SERVICE_ACCOUNT: inference
    INFERENCE_DOCKER_IMAGE: 'ghcr.io/predibase/lorax:387e17e'
    SERVICE_IMAGE_REPOSITORY: 128336707324.dkr.ecr.us-east-1.amazonaws.com/service
    SERVICE_NAMESPACE: services
    SERVICE_SERVICE_ACCOUNT: service
    STORAGE_SERVICE: s3

synapse:
  configMapData:
    ENV: prod
    APPS_URL: 'http://router.fission.svc.cluster.local:80'
    INFERENCES_NAMESPACE: inferences
    STORAGE_SERVICE: s3

ui:
  configMapData:
    ENV: prod