dynamiq:
  apps:
    namespace: apps

  imageCredentials:
    registry: https://index.docker.io/v1/
    username: ""
    password: ""

  runtime:
    name: app-env-v150
    image: dynamiqai/app-runtime:1.0.6
    env:
      - name: ENV
        value: prod
    poolsize: 3
    resources:
      limits:
        cpu: "1"
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 512Mi